[build]
  command = "NITRO_PRESET=netlify npx nuxi build"
  publish = ".output/public"
  functions = ".netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
